#!/bin/bash
if [[ $# -eq 0 ]] ; then
    echo "Missing directory parameter. Usage: ./html-starter project_dir"
    exit 1
fi

git clone https://github.com/Glitchbone/html-starter-template.git $1
rm -rf $1/.git
compass watch $1/src